// Generated by CoffeeScript 1.6.3
/*
  非ステートパターンの場合
*/

$(function() {
  var selected;
  selected = null;
  $("#list li").mousedown(function() {
    if (!selected) {
      selected = this;
      return $("#drag-item").text($(selected).text()).show();
    }
  });
  $("#list").mousemove(function(event) {
    var target;
    target = event.target;
    if (target.tagName === "LI" && selected) {
      $("#drag-item").css({
        left: event.pageX + 2,
        top: event.pageY + 2
      });
      $("#list li").removeClass("drag-over");
      return $(target).addClass("drag-over");
    }
  });
  return $("#list").mouseup(function(event) {
    var target;
    target = event.target;
    if (target.tagName === "LI" && selected) {
      $(target).after(selected);
      selected = null;
      $("#list li").removeClass("drag-over");
      return $("#drag-item").hide();
    }
  });
});
